language: node_js
node_js:
  # - 0.10 # testing locally only for 0.10 (nyc fails)
  # - 0.12 # assume 0.12 works if 0.10 does.
  - 4
  - 6

os:
  - linux
  - osx

install:
  - npm -g install npm@3
  - npm install
  # install all resolver deps
  - "for resolver in ./resolvers/*; do cd $resolver && npm install && cd ../..; done"

script:
  - "npm test"
  - "for resolver in ./resolvers/*; do cd $resolver && npm test && cd ../..; done"

after_success:
  - npm run coveralls
